# This is a basic workflow to help you get started with Actions

name: docker_action:0.0

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string : weekly,Monday,10:00 #m h d/m m d/w 
    - cron:  '00 10 * * 1'

jobs:
  docker-run-action:
    runs-on: ubuntu-latest
    container:
      image: tamboraorg/crecoding:2020.0
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - ${{ github.workspace }}:/cre/R
    steps:
      - uses: actions/checkout@v3
#        with:
#          ref: master
##      - name: Install pandoc
##        run: (apt-get -y --no-install-recommends install pandoc) 
##      - name: Install markdown
##        run: (R -e "install.packages('rmarkdown')")
      - name: Run knitr
        run: (R -e "rmarkdown::render('/cre/R/README.Rmd')")
      - name: Submit changes       
        uses: EndBug/add-and-commit@v9
